### ISSUE TITLE
Version 0.5 roadmap

### ISSUE THREAD

**Issue by neilalexander** [yggdrasil-network/yggdrasil-go#904]
The following are things we have identified as desirable for v0.5:

- [ ] **Revised soft-state routing**

This is largely done in Ironwood already to simplify path setup. It also involves replacing the source routing with opportunistic greedy tree routing, so the stretch should be largely the same, but will eliminate #851.

- [ ] **Revised session crypto**

Replace the current end-to-end session encryption with something more standard, like Noise or DTLS — audited libraries would be even better. The current key rotation is also a bit too aggressive and that hurts performance so it would be nice to have something more resource-friendly.

- [ ] **Mutual peer authentication**

Either some kind of shared-key authentication or passwords, where you can ensure that you only accept peerings from other nodes that also share one of the relevant keys. This would make it much easier to avoid peerings from nodes you don't want but also be much more user-friendly than having to maintain `AllowedPublicKeys` which is very manual.

- [ ] **Network segregation**

A shared network key, included in the tree announcements, will ensure that two nodes that peer with what should be segregated networks will ignore each other. This should make it much easier to operate private Yggdrasil meshes and not worry that they will end up accidentally peered to the public network.

- [ ] **Peer queues**

Something like `fq_codel` or even something naive (like matrix-org/pinecone#34), so that we can more fairly balance traffic around the network and reduce latency somewhat in congestion scenarios. Obviously we can't avoid the problems from TCP buffers but it might improve things slightly.

- [ ] **QUIC peerings**

Assuming the padding in QUIC doesn't end up being too terrible, we could use `quic-go` or something as an alternative peering transport. 

- [ ] **Fuzzing**

Support for fuzzing landed in Go 1.18 recently.
